[versions]
#agp = "8.13.1"
agp = "8.5.0"
google-services = "4.4.2"

#junit = "4.13.2"
#junitVersion = "1.3.0"
#espressoCore = "3.7.0"
#
#appcompat = "1.7.1"
#material = "1.13.0"
#constraintlayout = "2.2.1"
navigationFragment = "2.9.6"
navigationUi = "2.9.6"

appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"
recyclerview = "1.3.1"
cardview = "1.0.0"
gridlayout = "1.0.0"

osmdroid = "6.1.14"

okhttp = "4.10.0"
okio = "3.4.0"

lottie = "6.7.1"
volley = "1.2.1"

firebase-auth = "22.3.0"
firebase-firestore = "24.6.0"
firebase-analytics = "21.3.0"

gson = "2.10.1"

junit = "4.13.2"
androidx-junit = "1.1.5"
espresso-core = "3.5.1"
#navigation-fragment = "2.9.6"
#navigation-ui = "2.9.6"

[libraries]
#junit = { group = "junit", name = "junit", version.ref = "junit" }
#ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
#espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
#appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
#material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }

osmdroid = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroid" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebase-firestore" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }

volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

junit = { module = "junit:junit", version.ref = "junit" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
#navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation-fragment" }
#navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation-ui" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
